#!/bin/bash

cd "$(dirname "$BASH_SOURCE")"

[ -e all-popcon-results.txt.gz ] || wget popcon.debian.org/all-popcon-results.txt.gz

join \
  -o 1.2,0,2.2 \
  -t $'\t' \
  <(aptitude --disable-columns --display-format $'%p\t%c%a%M' search "$@" | sort --key 1,1) \
  <(zcat all-popcon-results.txt.gz | sed --quiet 's/Package: //;T;s/ \+\(.\{4\}[^ ] \|[^ ]\{6,\}\)/\t\1/;p' | sort --key 1,1) \
  | sort --numeric-sort --key 3 --field-separator $'\t' \
  | column -s $'\t' -t \
